### ISSUE TITLE
TravisCI Badge is Incorrect

### ISSUE THREAD

**Issue by blimmer** [Ibotta/asdf-brig#8]
There's something weird with the Travis CI badge on this repo's readme:

<img width="341" alt="Screen Shot 2020-01-26 at 8 27 03 AM" src="https://user-images.githubusercontent.com/630449/73137485-d2011a80-4015-11ea-9794-1e9d4039cdc4.png">

Maybe it has something to do with changing it from a private repo to public? I got tagged in https://github.com/asdf-vm/asdf-plugins/issues/183, that's how I noticed.

**Comment by elementalvoid** [comment]
Fixed via #11.
